<?php

namespace Database\Seeders;

use App\Models\Facility;
use App\Models\MapEdge;
use App\Models\MapNode;
use App\Models\Room;
use App\Models\RoomCategory;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class InteractiveMapSeeder extends Seeder
{
    /** Koreksi kotak hotspot agar pas dengan gambar denah. */
    private const HOTSPOT_FIXES = [
        'parkiran' => ['map_x' => 6.5, 'map_y' => 8.0, 'map_width' => 9.3, 'map_height' => 64.0],
        'gerbang-utama' => ['map_x' => 50.5, 'map_y' => 80.0, 'map_width' => 3.0, 'map_height' => 8.5],
        'musholla' => ['map_x' => 59.5, 'map_y' => 62.0, 'map_width' => 9.0, 'map_height' => 24.0],
        'xi-kul-3' => ['map_y' => 2.0, 'map_height' => 7.6],
        'xi-kul-2-utara' => ['map_y' => 2.0, 'map_height' => 7.6],
        'xi-kul-1' => ['map_y' => 2.0, 'map_height' => 7.6],
        'xi-rpl-3' => ['map_y' => 2.0, 'map_height' => 7.6],
        'xi-rpl-2' => ['map_y' => 2.0, 'map_height' => 7.6],
        'xi-rpl-1' => ['map_y' => 2.0, 'map_height' => 7.6],
        'uks' => ['map_x' => 76.6, 'map_width' => 7.5],
        'lab-dkv' => ['map_x' => 76.6, 'map_width' => 7.5],
    ];

    /** Foto ruangan memakai aset yang tersedia di Next.js (public/images). */
    private const ROOM_IMAGES = [
        'laboratorium-rpl' => '/images/fasilitas/rpl-1.jpg',
        'laboratorium-rpl-2' => '/images/fasilitas/rpl-2.jpg',
        'lab-dkv' => '/images/fasilitas/dkv-1.jpg',
        'lab-dkv-atas' => '/images/fasilitas/dkv-2.jpg',
        'lab-aphp' => '/images/fasilitas/aphp-1.jpg',
        'lab-tefa-bakery-aphp' => '/images/fasilitas/aphp-2.jpg',
        'lab-pastri-kuliner' => '/images/fasilitas/tb-3.jpg',
        'lab-kuliner' => '/images/fasilitas/tb-2.jpg',
        'praktik-r' => '/images/fasilitas/tb-1.jpg',
        'bank' => '/images/fasilitas/lps-1.jpg',
        'kantor-pusat' => '/images/sejarah/gedung.jpg',
        'gerbang-utama' => '/images/sejarah/gedung.jpg',
    ];

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Disable foreign keys to cleanly refresh tables
        Schema::disableForeignKeyConstraints();
        Facility::truncate();
        Room::truncate();
        MapEdge::truncate();
        MapNode::truncate();
        RoomCategory::truncate();
        Schema::enableForeignKeyConstraints();

        // 1. Categories
        $categoriesData = [
            ['name' => 'Lab & Bengkel', 'slug' => 'lab-bengkel', 'icon' => 'laptop'],
            ['name' => 'Ruang Kelas', 'slug' => 'ruang-kelas', 'icon' => 'academic-cap'],
            ['name' => 'Fasilitas & Penunjang', 'slug' => 'fasilitas', 'icon' => 'building-library'],
            ['name' => 'Kantor & Tata Usaha', 'slug' => 'kantor', 'icon' => 'briefcase'],
            ['name' => 'Area Olahraga & Terbuka', 'slug' => 'area-terbuka', 'icon' => 'sparkles'],
            ['name' => 'Lainnya', 'slug' => 'lainnya', 'icon' => 'ellipsis-horizontal'],
        ];

        $categories = [];
        foreach ($categoriesData as $cat) {
            $categories[$cat['slug']] = RoomCategory::create($cat);
        }

        // 2. Jaringan jalur pejalan kaki (node & ruas koridor bernama)
        $walkway = new CampusWalkwaySeeder;
        $walkway->run();

        // 4. PRECISE ROOM DATA MATCHING EVERY BOX ON THE REAL FLOORPLAN
        $rooms = [
            // SISI BARAT (PARKIRAN)
            [
                'name' => 'Parkiran Sekolah',
                'slug' => 'parkiran',
                'building_name' => 'Sisi Barat Kampus',
                'category_id' => $categories['fasilitas']->id,
                'description' => 'Area parkir teratur untuk kendaraan siswa, guru, dan tamu sekolah.',
                'image' => 'rooms/parkiran.jpg',
                'open_hours' => '06.00 - 18.00 WIB',
                'is_active' => true,
                'map_x' => 3.5, 'map_y' => 7.0, 'map_width' => 12.0, 'map_height' => 72.0,
                'facilities' => [
                    ['name' => 'Kapasitas 500+ Motor', 'quantity' => 500],
                    ['name' => 'CCTV 24 Jam', 'quantity' => 4],
                ],
            ],

            // SISI SELATAN (DEPAN)
            [
                'name' => 'Bursa Kerja Khusus (BKK)',
                'slug' => 'bkk',
                'building_name' => 'Gedung Sayap Depan Kiri',
                'category_id' => $categories['kantor']->id,
                'description' => 'Layanan informasi lowongan kerja, rekrutmen industri, dan penyaluran kerja alumni.',
                'image' => 'rooms/kantor.jpg',
                'open_hours' => '07.30 - 15.30 WIB',
                'is_active' => true,
                'map_x' => 18.2, 'map_y' => 80.5, 'map_width' => 2.8, 'map_height' => 7.5,
                'facilities' => [['name' => 'Meja Konseling Karir', 'quantity' => 3]],
            ],
            [
                'name' => 'Koperasi Siswa (KOP)',
                'slug' => 'kop',
                'building_name' => 'Gedung Sayap Depan Kiri',
                'category_id' => $categories['fasilitas']->id,
                'description' => 'Menyediakan alat tulis, seragam, atribut sekolah, dan kebutuhan harian siswa.',
                'image' => 'rooms/kantin.jpg',
                'open_hours' => '07.00 - 15.30 WIB',
                'is_active' => true,
                'map_x' => 21.0, 'map_y' => 80.5, 'map_width' => 2.8, 'map_height' => 7.5,
                'facilities' => [['name' => 'Etalase Toko', 'quantity' => 4]],
            ],
            [
                'name' => 'Mini Bank Sekolah (BANK)',
                'slug' => 'bank',
                'building_name' => 'Gedung Sayap Depan Kiri',
                'category_id' => $categories['fasilitas']->id,
                'description' => 'Laboratorium praktik perbankan dan transaksi keuangan siswa.',
                'image' => 'rooms/kantor.jpg',
                'open_hours' => '07.30 - 14.30 WIB',
                'is_active' => true,
                'map_x' => 23.8, 'map_y' => 80.5, 'map_width' => 2.8, 'map_height' => 7.5,
                'facilities' => [['name' => 'Teller Counter', 'quantity' => 2]],
            ],
            [
                'name' => 'Kantor Kepala Sekolah & TU',
                'slug' => 'kantor-pusat',
                'building_name' => 'Gedung Utama Depan',
                'category_id' => $categories['kantor']->id,
                'description' => 'Pusat layanan administrasi sekolah, ruang kepala sekolah, staf tata usaha, dan ruang tamu.',
                'image' => 'rooms/kantor.jpg',
                'open_hours' => '07.00 - 16.00 WIB',
                'is_active' => true,
                'map_x' => 28.5, 'map_y' => 72.0, 'map_width' => 18.5, 'map_height' => 14.5,
                'facilities' => [
                    ['name' => 'Meja Layanan Tata Usaha', 'quantity' => 8],
                    ['name' => 'Ruang Kepala Sekolah', 'quantity' => 1],
                ],
            ],
            [
                'name' => 'Pos Satpam & Gerbang Utama',
                'slug' => 'gerbang-utama',
                'building_name' => 'Pintu Masuk Depan',
                'category_id' => $categories['fasilitas']->id,
                'description' => 'Akses gerbang utama keluar masuk warga sekolah dan tamu dengan penjagaan satpam 24 jam.',
                'image' => 'images/hero-bg.jpg',
                'open_hours' => '24 Jam',
                'is_active' => true,
                'map_x' => 50.0, 'map_y' => 79.5, 'map_width' => 4.0, 'map_height' => 8.5,
                'facilities' => [
                    ['name' => 'Pos Keamanan', 'quantity' => 1],
                    ['name' => 'Palang Gerbang Otomatis', 'quantity' => 2],
                ],
            ],
            [
                'name' => 'Musholla Al-Ikhlas',
                'slug' => 'musholla',
                'building_name' => 'Area Tengah Kampus',
                'category_id' => $categories['fasilitas']->id,
                'description' => 'Sarana ibadah sholat berjamaah lima waktu, sholat dhuha bersama, dan kegiatan keagamaan.',
                'image' => 'rooms/mushola.jpg',
                'open_hours' => '05.00 - 18.30 WIB',
                'is_active' => true,
                'map_x' => 59.5, 'map_y' => 62.0, 'map_width' => 9.5, 'map_height' => 22.0,
                'facilities' => [
                    ['name' => 'Tempat Wudhu Pria & Wanita', 'quantity' => 2],
                    ['name' => 'Karpet Sajadah', 'quantity' => 12],
                ],
            ],

            // SAYAP BARAT (DKV & LPS)
            [
                'name' => 'Kelas X DKV 2',
                'slug' => 'x-dkv-2',
                'building_name' => 'Gedung Barat Lantai 2',
                'category_id' => $categories['ruang-kelas']->id,
                'description' => 'Ruang kelas teori untuk siswa kompetensi keahlian Desain Komunikasi Visual tingkat X.',
                'image' => 'rooms/kelas-rpl.jpg',
                'open_hours' => '07.00 - 15.30 WIB',
                'is_active' => true,
                'map_x' => 19.0, 'map_y' => 34.0, 'map_width' => 4.4, 'map_height' => 8.0,
                'facilities' => [['name' => 'Smart Display & Meja Siswa', 'quantity' => 36]],
            ],
            [
                'name' => 'Kelas XII DKV 2 (Barat)',
                'slug' => 'xii-dkv-2-barat',
                'building_name' => 'Gedung Barat Lantai 2',
                'category_id' => $categories['ruang-kelas']->id,
                'description' => 'Ruang kelas teori tingkat XII jurusan DKV.',
                'image' => 'rooms/kelas-rpl.jpg',
                'open_hours' => '07.00 - 15.30 WIB',
                'is_active' => true,
                'map_x' => 23.4, 'map_y' => 34.0, 'map_width' => 4.4, 'map_height' => 8.0,
                'facilities' => [['name' => 'Smart TV 55"', 'quantity' => 1]],
            ],
            [
                'name' => 'Kelas XII DKV 1 (Kiri)',
                'slug' => 'xii-dkv-1-kiri',
                'building_name' => 'Gedung Barat Lantai 2',
                'category_id' => $categories['ruang-kelas']->id,
                'description' => 'Ruang kelas teori tingkat XII DKV 1.',
                'image' => 'rooms/kelas-rpl.jpg',
                'open_hours' => '07.00 - 15.30 WIB',
                'is_active' => true,
                'map_x' => 19.0, 'map_y' => 42.0, 'map_width' => 4.4, 'map_height' => 8.0,
                'facilities' => [['name' => 'Meja & Kursi Siswa', 'quantity' => 36]],
            ],
            [
                'name' => 'Kelas XII DKV 1 (Kanan)',
                'slug' => 'xii-dkv-1-kanan',
                'building_name' => 'Gedung Barat Lantai 2',
                'category_id' => $categories['ruang-kelas']->id,
                'description' => 'Ruang kelas teori tingkat XII DKV 1.',
                'image' => 'rooms/kelas-rpl.jpg',
                'open_hours' => '07.00 - 15.30 WIB',
                'is_active' => true,
                'map_x' => 23.4, 'map_y' => 42.0, 'map_width' => 4.4, 'map_height' => 8.0,
                'facilities' => [['name' => 'Meja & Kursi Siswa', 'quantity' => 36]],
            ],
            [
                'name' => 'Kelas XII LPS 2 (Kiri)',
                'slug' => 'xii-lps-2-kiri',
                'building_name' => 'Gedung Barat Lantai 1',
                'category_id' => $categories['ruang-kelas']->id,
                'description' => 'Ruang kelas pembelajaran teori Layanan Perbankan Syariah.',
                'image' => 'rooms/kelas-rpl.jpg',
                'open_hours' => '07.00 - 15.30 WIB',
                'is_active' => true,
                'map_x' => 19.0, 'map_y' => 53.0, 'map_width' => 4.4, 'map_height' => 9.0,
                'facilities' => [['name' => 'Proyektor & Whiteboard', 'quantity' => 1]],
            ],
            [
                'name' => 'Kelas XII LPS 2 (Kanan)',
                'slug' => 'xii-lps-2-kanan',
                'building_name' => 'Gedung Barat Lantai 1',
                'category_id' => $categories['ruang-kelas']->id,
                'description' => 'Ruang kelas pembelajaran teori Layanan Perbankan Syariah.',
                'image' => 'rooms/kelas-rpl.jpg',
                'open_hours' => '07.00 - 15.30 WIB',
                'is_active' => true,
                'map_x' => 23.4, 'map_y' => 53.0, 'map_width' => 4.4, 'map_height' => 9.0,
                'facilities' => [['name' => 'Proyektor & Whiteboard', 'quantity' => 1]],
            ],
            [
                'name' => 'Kelas XII LPS 1 (Kiri)',
                'slug' => 'xii-lps-1-kiri',
                'building_name' => 'Gedung Barat Lantai 1',
                'category_id' => $categories['ruang-kelas']->id,
                'description' => 'Ruang kelas pembelajaran teori Layanan Perbankan Syariah.',
                'image' => 'rooms/kelas-rpl.jpg',
                'open_hours' => '07.00 - 15.30 WIB',
                'is_active' => true,
                'map_x' => 19.0, 'map_y' => 62.0, 'map_width' => 4.4, 'map_height' => 9.0,
                'facilities' => [['name' => 'Meja Belajar Siswa', 'quantity' => 36]],
            ],
            [
                'name' => 'Kelas XII LPS 1 (Kanan)',
                'slug' => 'xii-lps-1-kanan',
                'building_name' => 'Gedung Barat Lantai 1',
                'category_id' => $categories['ruang-kelas']->id,
                'description' => 'Ruang kelas pembelajaran teori Layanan Perbankan Syariah.',
                'image' => 'rooms/kelas-rpl.jpg',
                'open_hours' => '07.00 - 15.30 WIB',
                'is_active' => true,
                'map_x' => 23.4, 'map_y' => 62.0, 'map_width' => 4.4, 'map_height' => 9.0,
                'facilities' => [['name' => 'Meja Belajar Siswa', 'quantity' => 36]],
            ],

            // SAYAP BARAT LAUT (APHP, KANTIN, PASTRI, TEFA)
            [
                'name' => 'Lab Pengolahan APHP',
                'slug' => 'lab-aphp',
                'building_name' => 'Gedung Sayap Barat Laut',
                'category_id' => $categories['lab-bengkel']->id,
                'description' => 'Laboratorium pengolahan hasil pertanian dan pangan untuk uji mutu produk dan pengalengan.',
                'image' => 'rooms/lab-aphp.jpg',
                'open_hours' => '07.00 - 16.00 WIB',
                'is_active' => true,
                'map_x' => 20.0, 'map_y' => 2.5, 'map_width' => 7.2, 'map_height' => 7.5,
                'facilities' => [['name' => 'Mesin Vacuum Sealer', 'quantity' => 4]],
            ],
            [
                'name' => 'Kantin Sehat Sekolah',
                'slug' => 'kantin',
                'building_name' => 'Area Sayap Barat Laut',
                'category_id' => $categories['fasilitas']->id,
                'description' => 'Pusat kuliner sekolah yang menyediakan aneka makanan dan minuman bersih dan higienis.',
                'image' => 'rooms/kantin.jpg',
                'open_hours' => '06.30 - 16.00 WIB',
                'is_active' => true,
                'map_x' => 27.8, 'map_y' => 2.5, 'map_width' => 8.5, 'map_height' => 7.5,
                'facilities' => [['name' => 'Stand Makanan & Meja Makan', 'quantity' => 20]],
            ],
            [
                'name' => 'Lab Pastri Kuliner',
                'slug' => 'lab-pastri-kuliner',
                'building_name' => 'Gedung Sayap Barat Laut',
                'category_id' => $categories['lab-bengkel']->id,
                'description' => 'Kitchen lab berstandar hotel untuk pembuatan aneka kue, roti, dan pastry.',
                'image' => 'rooms/lab-kuliner.jpg',
                'open_hours' => '07.00 - 16.00 WIB',
                'is_active' => true,
                'map_x' => 37.0, 'map_y' => 2.5, 'map_width' => 11.2, 'map_height' => 7.5,
                'facilities' => [['name' => 'Oven Convection & Mixer Besar', 'quantity' => 3]],
            ],
            [
                'name' => 'Kolam Edukasi & Rekreasi',
                'slug' => 'kolam',
                'building_name' => 'Area Taman Barat Laut',
                'category_id' => $categories['fasilitas']->id,
                'description' => 'Kolam ikan edukasi budidaya dan penyejuk lingkungan taman sekolah.',
                'image' => 'rooms/lapangan.jpg',
                'open_hours' => '07.00 - 16.00 WIB',
                'is_active' => true,
                'map_x' => 24.5, 'map_y' => 12.0, 'map_width' => 12.0, 'map_height' => 6.8,
                'facilities' => [['name' => 'Kolam Ikan & Taman Hijau', 'quantity' => 1]],
            ],
            [
                'name' => 'Lab TEFA Bakery APHP',
                'slug' => 'lab-tefa-bakery-aphp',
                'building_name' => 'Gedung Teaching Factory APHP',
                'category_id' => $categories['lab-bengkel']->id,
                'description' => 'Pusat Teaching Factory produksi roti, bakery, dan minuman sari buah berstandar industri.',
                'image' => 'rooms/lab-aphp.jpg',
                'open_hours' => '07.00 - 16.00 WIB',
                'is_active' => true,
                'map_x' => 37.5, 'map_y' => 11.5, 'map_width' => 5.8, 'map_height' => 7.5,
                'facilities' => [['name' => 'Lini Produksi Bakery Standar DUDI', 'quantity' => 1]],
            ],
            [
                'name' => 'Kelas XI APHP 2 (Atas)',
                'slug' => 'xi-aphp-2-atas',
                'building_name' => 'Gedung APHP',
                'category_id' => $categories['ruang-kelas']->id,
                'description' => 'Ruang kelas teori untuk siswa kompetensi keahlian APHP tingkat XI.',
                'image' => 'rooms/kelas-rpl.jpg',
                'open_hours' => '07.00 - 15.30 WIB',
                'is_active' => true,
                'map_x' => 43.3, 'map_y' => 11.5, 'map_width' => 5.8, 'map_height' => 7.5,
                'facilities' => [['name' => 'Meja & Kursi Siswa', 'quantity' => 36]],
            ],
            [
                'name' => 'Kelas X APHP 1',
                'slug' => 'x-aphp-1',
                'building_name' => 'Gedung APHP Lantai 2',
                'category_id' => $categories['ruang-kelas']->id,
                'description' => 'Ruang kelas teori siswa tingkat X APHP 1.',
                'image' => 'rooms/kelas-rpl.jpg',
                'open_hours' => '07.00 - 15.30 WIB',
                'is_active' => true,
                'map_x' => 26.5, 'map_y' => 20.0, 'map_width' => 5.6, 'map_height' => 5.5,
                'facilities' => [['name' => 'Meja Belajar Siswa', 'quantity' => 36]],
            ],
            [
                'name' => 'Kelas XI APHP 1',
                'slug' => 'xi-aphp-1',
                'building_name' => 'Gedung APHP Lantai 2',
                'category_id' => $categories['ruang-kelas']->id,
                'description' => 'Ruang kelas teori siswa tingkat XI APHP 1.',
                'image' => 'rooms/kelas-rpl.jpg',
                'open_hours' => '07.00 - 15.30 WIB',
                'is_active' => true,
                'map_x' => 32.1, 'map_y' => 20.0, 'map_width' => 5.6, 'map_height' => 5.5,
                'facilities' => [['name' => 'Smart Display', 'quantity' => 1]],
            ],
            [
                'name' => 'Kelas XI Kuliner 2 (Barat)',
                'slug' => 'xi-kul-2-barat',
                'building_name' => 'Gedung Kuliner Lantai 2',
                'category_id' => $categories['ruang-kelas']->id,
                'description' => 'Ruang kelas teori siswa tingkat XI Kuliner 2.',
                'image' => 'rooms/kelas-rpl.jpg',
                'open_hours' => '07.00 - 15.30 WIB',
                'is_active' => true,
                'map_x' => 37.7, 'map_y' => 20.0, 'map_width' => 5.6, 'map_height' => 5.5,
                'facilities' => [['name' => 'Meja Siswa', 'quantity' => 36]],
            ],
            [
                'name' => 'Kelas XII Kuliner 2 (Barat)',
                'slug' => 'xii-kul-2-barat',
                'building_name' => 'Gedung Kuliner Lantai 2',
                'category_id' => $categories['ruang-kelas']->id,
                'description' => 'Ruang kelas teori siswa tingkat XII Kuliner 2.',
                'image' => 'rooms/kelas-rpl.jpg',
                'open_hours' => '07.00 - 15.30 WIB',
                'is_active' => true,
                'map_x' => 43.3, 'map_y' => 20.0, 'map_width' => 5.6, 'map_height' => 5.5,
                'facilities' => [['name' => 'Meja Siswa', 'quantity' => 36]],
            ],
            [
                'name' => 'Kelas XII APHP 1 (Kiri)',
                'slug' => 'xii-aphp-1-kiri',
                'building_name' => 'Gedung APHP Lantai 1',
                'category_id' => $categories['ruang-kelas']->id,
                'description' => 'Ruang kelas teori siswa tingkat akhir APHP.',
                'image' => 'rooms/kelas-rpl.jpg',
                'open_hours' => '07.00 - 15.30 WIB',
                'is_active' => true,
                'map_x' => 26.5, 'map_y' => 25.5, 'map_width' => 5.6, 'map_height' => 6.0,
                'facilities' => [['name' => 'Meja & Kursi', 'quantity' => 36]],
            ],
            [
                'name' => 'Kelas XII APHP 1 (Kanan)',
                'slug' => 'xii-aphp-1-kanan',
                'building_name' => 'Gedung APHP Lantai 1',
                'category_id' => $categories['ruang-kelas']->id,
                'description' => 'Ruang kelas teori siswa tingkat akhir APHP.',
                'image' => 'rooms/kelas-rpl.jpg',
                'open_hours' => '07.00 - 15.30 WIB',
                'is_active' => true,
                'map_x' => 32.1, 'map_y' => 25.5, 'map_width' => 5.6, 'map_height' => 6.0,
                'facilities' => [['name' => 'Meja & Kursi', 'quantity' => 36]],
            ],
            [
                'name' => 'Kelas XII DKV 2 (Utara)',
                'slug' => 'xii-dkv-2-utara',
                'building_name' => 'Gedung Utara',
                'category_id' => $categories['ruang-kelas']->id,
                'description' => 'Ruang kelas teori untuk siswa XII DKV 2.',
                'image' => 'rooms/kelas-rpl.jpg',
                'open_hours' => '07.00 - 15.30 WIB',
                'is_active' => true,
                'map_x' => 37.7, 'map_y' => 25.5, 'map_width' => 5.6, 'map_height' => 6.0,
                'facilities' => [['name' => 'Whiteboard & Proyektor', 'quantity' => 1]],
            ],
            [
                'name' => 'Kelas XI APHP 2 (Bawah)',
                'slug' => 'xi-aphp-2-bawah',
                'building_name' => 'Gedung APHP Lantai 1',
                'category_id' => $categories['ruang-kelas']->id,
                'description' => 'Ruang kelas teori siswa XI APHP 2.',
                'image' => 'rooms/kelas-rpl.jpg',
                'open_hours' => '07.00 - 15.30 WIB',
                'is_active' => true,
                'map_x' => 43.3, 'map_y' => 25.5, 'map_width' => 5.6, 'map_height' => 6.0,
                'facilities' => [['name' => 'Meja Siswa', 'quantity' => 36]],
            ],

            // SAYAP TENGAH (KIRI: X KUL 3, X RPL 1, 2, 3 | KANAN: XII KUL 3, XII RPL 1, 2, 3)
            [
                'name' => 'Kelas X Kuliner 3 (Kiri)',
                'slug' => 'x-kul-3-kiri',
                'building_name' => 'Gedung Tengah Lantai 2',
                'category_id' => $categories['ruang-kelas']->id,
                'description' => 'Ruang kelas pembelajaran teori siswa tingkat X Kuliner 3.',
                'image' => 'rooms/kelas-rpl.jpg',
                'open_hours' => '07.00 - 15.30 WIB',
                'is_active' => true,
                'map_x' => 48.2, 'map_y' => 34.0, 'map_width' => 4.2, 'map_height' => 8.5,
                'facilities' => [['name' => 'Meja & Kursi Siswa', 'quantity' => 36]],
            ],
            [
                'name' => 'Kelas XII Kuliner 3 (Kanan)',
                'slug' => 'xii-kul-3-kanan',
                'building_name' => 'Gedung Tengah Lantai 2',
                'category_id' => $categories['ruang-kelas']->id,
                'description' => 'Ruang kelas pembelajaran teori siswa tingkat XII Kuliner 3.',
                'image' => 'rooms/kelas-rpl.jpg',
                'open_hours' => '07.00 - 15.30 WIB',
                'is_active' => true,
                'map_x' => 52.4, 'map_y' => 34.0, 'map_width' => 4.2, 'map_height' => 8.5,
                'facilities' => [['name' => 'Meja & Kursi Siswa', 'quantity' => 36]],
            ],
            [
                'name' => 'Kelas X RPL 1',
                'slug' => 'x-rpl-1',
                'building_name' => 'Gedung Tengah Lantai 1',
                'category_id' => $categories['ruang-kelas']->id,
                'description' => 'Ruang kelas pembelajaran teori dan koding dasar untuk tingkat X RPL 1.',
                'image' => 'rooms/kelas-rpl.jpg',
                'open_hours' => '07.00 - 15.30 WIB',
                'is_active' => true,
                'map_x' => 48.2, 'map_y' => 43.0, 'map_width' => 4.2, 'map_height' => 9.0,
                'facilities' => [
                    ['name' => 'Smart Display 55"', 'quantity' => 1],
                    ['name' => 'Meja Siswa', 'quantity' => 36],
                ],
            ],
            [
                'name' => 'Kelas XII RPL 1',
                'slug' => 'xii-rpl-1',
                'building_name' => 'Gedung Tengah Lantai 1',
                'category_id' => $categories['ruang-kelas']->id,
                'description' => 'Ruang kelas pembelajaran teori untuk siswa tingkat akhir XII RPL 1.',
                'image' => 'rooms/kelas-rpl.jpg',
                'open_hours' => '07.00 - 15.30 WIB',
                'is_active' => true,
                'map_x' => 52.4, 'map_y' => 43.0, 'map_width' => 4.2, 'map_height' => 9.0,
                'facilities' => [['name' => 'Meja & Kursi Siswa', 'quantity' => 36]],
            ],
            [
                'name' => 'Kelas X RPL 2',
                'slug' => 'x-rpl-2',
                'building_name' => 'Gedung Tengah Lantai 1',
                'category_id' => $categories['ruang-kelas']->id,
                'description' => 'Ruang kelas pembelajaran teori komputasi untuk siswa tingkat X RPL 2.',
                'image' => 'rooms/kelas-rpl.jpg',
                'open_hours' => '07.00 - 15.30 WIB',
                'is_active' => true,
                'map_x' => 48.2, 'map_y' => 53.0, 'map_width' => 4.2, 'map_height' => 9.0,
                'facilities' => [['name' => 'Proyektor LCD', 'quantity' => 1]],
            ],
            [
                'name' => 'Kelas XII RPL 2',
                'slug' => 'xii-rpl-2',
                'building_name' => 'Gedung Tengah Lantai 1',
                'category_id' => $categories['ruang-kelas']->id,
                'description' => 'Ruang kelas pembelajaran teori untuk siswa tingkat akhir XII RPL 2.',
                'image' => 'rooms/kelas-rpl.jpg',
                'open_hours' => '07.00 - 15.30 WIB',
                'is_active' => true,
                'map_x' => 52.4, 'map_y' => 53.0, 'map_width' => 4.2, 'map_height' => 9.0,
                'facilities' => [['name' => 'Meja Siswa', 'quantity' => 36]],
            ],
            [
                'name' => 'Kelas X RPL 3',
                'slug' => 'x-rpl-3',
                'building_name' => 'Gedung Tengah Lantai 1',
                'category_id' => $categories['ruang-kelas']->id,
                'description' => 'Ruang kelas pembelajaran teori untuk siswa tingkat X RPL 3.',
                'image' => 'rooms/kelas-rpl.jpg',
                'open_hours' => '07.00 - 15.30 WIB',
                'is_active' => true,
                'map_x' => 48.2, 'map_y' => 62.5, 'map_width' => 4.2, 'map_height' => 9.0,
                'facilities' => [['name' => 'Whiteboard & Meja Siswa', 'quantity' => 36]],
            ],
            [
                'name' => 'Kelas XII RPL 3',
                'slug' => 'xii-rpl-3',
                'building_name' => 'Gedung Tengah Lantai 1',
                'category_id' => $categories['ruang-kelas']->id,
                'description' => 'Ruang kelas pembelajaran teori untuk siswa tingkat akhir XII RPL 3.',
                'image' => 'rooms/kelas-rpl.jpg',
                'open_hours' => '07.00 - 15.30 WIB',
                'is_active' => true,
                'map_x' => 52.4, 'map_y' => 62.5, 'map_width' => 4.2, 'map_height' => 9.0,
                'facilities' => [['name' => 'Meja Siswa', 'quantity' => 36]],
            ],

            // SAYAP UTARA ATAS (KELAS XI & XII RPL / KULINER / LPS)
            [
                'name' => 'Kelas XI Kuliner 3',
                'slug' => 'xi-kul-3',
                'building_name' => 'Gedung Utara Lantai 2',
                'category_id' => $categories['ruang-kelas']->id,
                'description' => 'Ruang kelas teori kejuruan Kuliner tingkat XI.',
                'image' => 'rooms/kelas-rpl.jpg',
                'open_hours' => '07.00 - 15.30 WIB',
                'is_active' => true,
                'map_x' => 58.0, 'map_y' => 2.5, 'map_width' => 5.5, 'map_height' => 8.0,
                'facilities' => [['name' => 'Meja Siswa', 'quantity' => 36]],
            ],
            [
                'name' => 'Kelas XI Kuliner 2',
                'slug' => 'xi-kul-2-utara',
                'building_name' => 'Gedung Utara Lantai 2',
                'category_id' => $categories['ruang-kelas']->id,
                'description' => 'Ruang kelas teori siswa XI Kuliner 2.',
                'image' => 'rooms/kelas-rpl.jpg',
                'open_hours' => '07.00 - 15.30 WIB',
                'is_active' => true,
                'map_x' => 63.5, 'map_y' => 2.5, 'map_width' => 5.5, 'map_height' => 8.0,
                'facilities' => [['name' => 'Meja Siswa', 'quantity' => 36]],
            ],
            [
                'name' => 'Kelas XI Kuliner 1',
                'slug' => 'xi-kul-1',
                'building_name' => 'Gedung Utara Lantai 2',
                'category_id' => $categories['ruang-kelas']->id,
                'description' => 'Ruang kelas teori siswa XI Kuliner 1.',
                'image' => 'rooms/kelas-rpl.jpg',
                'open_hours' => '07.00 - 15.30 WIB',
                'is_active' => true,
                'map_x' => 69.0, 'map_y' => 2.5, 'map_width' => 5.0, 'map_height' => 8.0,
                'facilities' => [['name' => 'Meja Siswa', 'quantity' => 36]],
            ],
            [
                'name' => 'Kelas XI RPL 3',
                'slug' => 'xi-rpl-3',
                'building_name' => 'Gedung Utara Lantai 2',
                'category_id' => $categories['ruang-kelas']->id,
                'description' => 'Ruang kelas teori untuk jurusan RPL tingkat XI.',
                'image' => 'rooms/kelas-rpl.jpg',
                'open_hours' => '07.00 - 15.30 WIB',
                'is_active' => true,
                'map_x' => 74.0, 'map_y' => 2.5, 'map_width' => 5.0, 'map_height' => 8.0,
                'facilities' => [['name' => 'Smart Display', 'quantity' => 1]],
            ],
            [
                'name' => 'Kelas XI RPL 2',
                'slug' => 'xi-rpl-2',
                'building_name' => 'Gedung Utara Lantai 2',
                'category_id' => $categories['ruang-kelas']->id,
                'description' => 'Ruang kelas teori untuk siswa kejuruan RPL tingkat XI.',
                'image' => 'rooms/kelas-rpl.jpg',
                'open_hours' => '07.00 - 15.30 WIB',
                'is_active' => true,
                'map_x' => 79.0, 'map_y' => 2.5, 'map_width' => 5.0, 'map_height' => 8.0,
                'facilities' => [['name' => 'Meja & Kursi Siswa', 'quantity' => 36]],
            ],
            [
                'name' => 'Kelas XI RPL 1',
                'slug' => 'xi-rpl-1',
                'building_name' => 'Gedung Utara Lantai 2',
                'category_id' => $categories['ruang-kelas']->id,
                'description' => 'Ruang kelas teori siswa tingkat XI RPL 1.',
                'image' => 'rooms/kelas-rpl.jpg',
                'open_hours' => '07.00 - 15.30 WIB',
                'is_active' => true,
                'map_x' => 84.0, 'map_y' => 2.5, 'map_width' => 5.0, 'map_height' => 8.0,
                'facilities' => [['name' => 'Meja Siswa', 'quantity' => 36]],
            ],
            [
                'name' => 'Kelas XII Kuliner 3',
                'slug' => 'xii-kul-3-utara',
                'building_name' => 'Gedung Utara Lantai 1',
                'category_id' => $categories['ruang-kelas']->id,
                'description' => 'Ruang kelas teori siswa tingkat akhir Kuliner.',
                'image' => 'rooms/kelas-rpl.jpg',
                'open_hours' => '07.00 - 15.30 WIB',
                'is_active' => true,
                'map_x' => 58.0, 'map_y' => 11.5, 'map_width' => 5.5, 'map_height' => 7.5,
                'facilities' => [['name' => 'Meja Siswa', 'quantity' => 36]],
            ],
            [
                'name' => 'Kelas XII Kuliner V2',
                'slug' => 'xii-kul-v2',
                'building_name' => 'Gedung Utara Lantai 1',
                'category_id' => $categories['ruang-kelas']->id,
                'description' => 'Ruang kelas teori siswa tingkat XII Kuliner.',
                'image' => 'rooms/kelas-rpl.jpg',
                'open_hours' => '07.00 - 15.30 WIB',
                'is_active' => true,
                'map_x' => 63.5, 'map_y' => 11.5, 'map_width' => 6.5, 'map_height' => 7.5,
                'facilities' => [['name' => 'Meja Siswa', 'quantity' => 36]],
            ],
            [
                'name' => 'Kelas XII LPS 1 (Utara)',
                'slug' => 'xii-lps-1-utara',
                'building_name' => 'Gedung Utara Lantai 1',
                'category_id' => $categories['ruang-kelas']->id,
                'description' => 'Ruang kelas teori jurusan Layanan Perbankan Syariah.',
                'image' => 'rooms/kelas-rpl.jpg',
                'open_hours' => '07.00 - 15.30 WIB',
                'is_active' => true,
                'map_x' => 70.0, 'map_y' => 11.5, 'map_width' => 6.0, 'map_height' => 7.5,
                'facilities' => [['name' => 'Meja Siswa', 'quantity' => 36]],
            ],

            // GEDUNG LAB RPL & AULA
            [
                'name' => 'Laboratorium RPL 1',
                'slug' => 'laboratorium-rpl',
                'building_name' => 'Gedung B Lantai 2 (RPL)',
                'category_id' => $categories['lab-bengkel']->id,
                'description' => 'Laboratorium komputer utama untuk praktik koding, web development, dan mobile application.',
                'image' => 'rooms/laboratorium-rpl.jpg',
                'open_hours' => '07.00 - 16.00 WIB',
                'is_active' => true,
                'map_x' => 60.0, 'map_y' => 20.5, 'map_width' => 11.5, 'map_height' => 5.5,
                'facilities' => [
                    ['name' => '36 PC Core i7 High End', 'quantity' => 36],
                    ['name' => 'Smart Screen & Proyektor', 'quantity' => 1],
                    ['name' => 'WiFi Dedicated 100 Mbps', 'quantity' => 1],
                    ['name' => 'AC Split 2 PK', 'quantity' => 2],
                ],
            ],
            [
                'name' => 'Laboratorium RPL 2',
                'slug' => 'laboratorium-rpl-2',
                'building_name' => 'Gedung B Lantai 2 (RPL)',
                'category_id' => $categories['lab-bengkel']->id,
                'description' => 'Laboratorium komputer lanjutan untuk database, server Linux, dan project-based learning.',
                'image' => 'rooms/laboratorium-rpl.jpg',
                'open_hours' => '07.00 - 16.00 WIB',
                'is_active' => true,
                'map_x' => 72.0, 'map_y' => 20.5, 'map_width' => 8.8, 'map_height' => 5.5,
                'facilities' => [
                    ['name' => 'Workstation Developer', 'quantity' => 36],
                    ['name' => 'Server Mini & Switch', 'quantity' => 2],
                ],
            ],
            [
                'name' => 'Aula Serbaguna (Barat)',
                'slug' => 'aula-barat',
                'building_name' => 'Gedung B Lantai 1',
                'category_id' => $categories['fasilitas']->id,
                'description' => 'Ruang pertemuan akbar sekolah untuk seminar industri, workshop, dan acara seni budaya.',
                'image' => 'rooms/aula.jpg',
                'open_hours' => '07.00 - 17.00 WIB',
                'is_active' => true,
                'map_x' => 60.0, 'map_y' => 26.0, 'map_width' => 10.4, 'map_height' => 6.5,
                'facilities' => [
                    ['name' => 'Panggung & Videotron', 'quantity' => 1],
                    ['name' => 'Kursi Tamu 150 Unit', 'quantity' => 150],
                ],
            ],
            [
                'name' => 'Aula Serbaguna (Timur)',
                'slug' => 'aula-timur',
                'building_name' => 'Gedung B Lantai 1',
                'category_id' => $categories['fasilitas']->id,
                'description' => 'Ruang pertemuan akbar sekolah untuk seminar industri, workshop, dan acara seni budaya.',
                'image' => 'rooms/aula.jpg',
                'open_hours' => '07.00 - 17.00 WIB',
                'is_active' => true,
                'map_x' => 70.4, 'map_y' => 26.0, 'map_width' => 10.4, 'map_height' => 6.5,
                'facilities' => [
                    ['name' => 'Kursi Tamu 150 Unit', 'quantity' => 150],
                ],
            ],

            // GEDUNG SAYAP TIMUR (PERPUSTAKAAN, UKS, FOOD, DKV, BK)
            [
                'name' => 'XII Unit 2 / Percetakan',
                'slug' => 'xii-unit-2-percetakan',
                'building_name' => 'Gedung Sayap Timur Lantai 2',
                'category_id' => $categories['fasilitas']->id,
                'description' => 'Unit produksi percetakan dan perpustakaan literasi sekolah.',
                'image' => 'rooms/perpustakaan.jpg',
                'open_hours' => '07.00 - 16.00 WIB',
                'is_active' => true,
                'map_x' => 75.2, 'map_y' => 34.0, 'map_width' => 5.8, 'map_height' => 16.5,
                'facilities' => [
                    ['name' => 'Koleksi 5000+ Buku', 'quantity' => 5000],
                    ['name' => 'Mesin Cetak Offset', 'quantity' => 2],
                ],
            ],
            [
                'name' => 'Lab Food & Kuliner (Tata Boga)',
                'slug' => 'lab-kuliner',
                'building_name' => 'Gedung Sayap Timur Lantai 2',
                'category_id' => $categories['lab-bengkel']->id,
                'description' => 'Kitchen lab berstandar restoran hotel berbintang untuk praktik memasak masakan nusantara dan kontinental.',
                'image' => 'rooms/lab-kuliner.jpg',
                'open_hours' => '07.00 - 16.00 WIB',
                'is_active' => true,
                'map_x' => 81.0, 'map_y' => 34.0, 'map_width' => 3.8, 'map_height' => 16.5,
                'facilities' => [
                    ['name' => 'Kompor Heavy Duty Stainless', 'quantity' => 8],
                    ['name' => 'Chiller & Freezer 4 Pintu', 'quantity' => 2],
                ],
            ],
            [
                'name' => 'Lab DKV (Studio Timur Atas)',
                'slug' => 'lab-dkv-atas',
                'building_name' => 'Gedung Sayap Timur Lantai 2',
                'category_id' => $categories['lab-bengkel']->id,
                'description' => 'Studio desain grafis, ilustrasi digital, dan rendering animasi.',
                'image' => 'rooms/lab-dkv.jpg',
                'open_hours' => '07.00 - 16.00 WIB',
                'is_active' => true,
                'map_x' => 84.8, 'map_y' => 34.0, 'map_width' => 3.2, 'map_height' => 16.5,
                'facilities' => [['name' => 'PC Editing GPU RTX 4060', 'quantity' => 15]],
            ],
            [
                'name' => 'Kelas XII LPS 1 (Timur Tengah)',
                'slug' => 'xii-lps-1-timur',
                'building_name' => 'Gedung Sayap Timur Lantai 1',
                'category_id' => $categories['ruang-kelas']->id,
                'description' => 'Ruang kelas teori kejuruan Layanan Perbankan Syariah.',
                'image' => 'rooms/kelas-rpl.jpg',
                'open_hours' => '07.00 - 15.30 WIB',
                'is_active' => true,
                'map_x' => 81.0, 'map_y' => 51.0, 'map_width' => 3.8, 'map_height' => 9.5,
                'facilities' => [['name' => 'Meja Siswa', 'quantity' => 36]],
            ],
            [
                'name' => 'Kelas XII UPS 1 / XII LPS 1 (Bawah Kiri)',
                'slug' => 'xii-ups-1-bawah',
                'building_name' => 'Gedung Sayap Timur Lantai 1',
                'category_id' => $categories['ruang-kelas']->id,
                'description' => 'Ruang kelas teori siswa tingkat akhir.',
                'image' => 'rooms/kelas-rpl.jpg',
                'open_hours' => '07.00 - 15.30 WIB',
                'is_active' => true,
                'map_x' => 71.2, 'map_y' => 60.5, 'map_width' => 5.5, 'map_height' => 7.0,
                'facilities' => [['name' => 'Meja Siswa', 'quantity' => 36]],
            ],
            [
                'name' => 'Unit Kesehatan Sekolah (UKS)',
                'slug' => 'uks',
                'building_name' => 'Gedung Sayap Timur Lantai 1',
                'category_id' => $categories['fasilitas']->id,
                'description' => 'Unit Kesehatan Sekolah untuk penanganan medis awal, obat darurat, dan istirahat siswa sakit.',
                'image' => 'rooms/uks.jpg',
                'open_hours' => '07.00 - 15.30 WIB',
                'is_active' => true,
                'map_x' => 76.7, 'map_y' => 60.5, 'map_width' => 7.8, 'map_height' => 7.0,
                'facilities' => [
                    ['name' => 'Tempat Tidur Medis Bersekat', 'quantity' => 3],
                    ['name' => 'Kotak P3K & Obat Darurat', 'quantity' => 2],
                    ['name' => 'Tabung Oksigen', 'quantity' => 1],
                ],
            ],
            [
                'name' => 'Ruang Praktik Resto (PRAKTIK R)',
                'slug' => 'praktik-r',
                'building_name' => 'Gedung Sayap Timur Lantai 1',
                'category_id' => $categories['lab-bengkel']->id,
                'description' => 'Laboratorium praktik pelayanan restoran, table setup, dan hospitality service.',
                'image' => 'rooms/lab-kuliner.jpg',
                'open_hours' => '07.00 - 16.00 WIB',
                'is_active' => true,
                'map_x' => 71.2, 'map_y' => 67.5, 'map_width' => 5.5, 'map_height' => 7.5,
                'facilities' => [['name' => 'Table Dining Setup & Bar Counter', 'quantity' => 1]],
            ],
            [
                'name' => 'Studio Foto & Podcast (Lab DKV)',
                'slug' => 'lab-dkv',
                'building_name' => 'Gedung Sayap Timur Lantai 1',
                'category_id' => $categories['lab-bengkel']->id,
                'description' => 'Studio fotografi, podcast, dan editing video dengan peralatan kamera 4K dan lighting profesional.',
                'image' => 'rooms/lab-dkv.jpg',
                'open_hours' => '07.00 - 16.00 WIB',
                'is_active' => true,
                'map_x' => 76.7, 'map_y' => 67.5, 'map_width' => 7.8, 'map_height' => 7.5,
                'facilities' => [
                    ['name' => 'Kamera DSLR & Mirrorless 4K', 'quantity' => 6],
                    ['name' => 'Lighting Studio & Softbox', 'quantity' => 8],
                ],
            ],
            [
                'name' => 'Ruang Bimbingan Konseling (BK)',
                'slug' => 'bk',
                'building_name' => 'Gedung Sayap Timur Lantai 1',
                'category_id' => $categories['kantor']->id,
                'description' => 'Ruang bimbingan konseling karir, pengembangan bakat minat, dan konsultasi siswa.',
                'image' => 'rooms/kantor.jpg',
                'open_hours' => '07.00 - 15.30 WIB',
                'is_active' => true,
                'map_x' => 84.8, 'map_y' => 60.5, 'map_width' => 3.5, 'map_height' => 15.0,
                'facilities' => [['name' => 'Ruang Konseling Privat', 'quantity' => 2]],
            ],

            // SISI TIMUR (LAPANGAN)
            [
                'name' => 'Lapangan Olahraga & Upacara',
                'slug' => 'lapangan-olahraga',
                'building_name' => 'Area Timur Sekolah',
                'category_id' => $categories['area-terbuka']->id,
                'description' => 'Lapangan serbaguna untuk upacara bendera, senam bersama, futsal, basket, voli, dan event pameran akbar.',
                'image' => 'rooms/lapangan.jpg',
                'open_hours' => '06.00 - 18.00 WIB',
                'is_active' => true,
                'map_x' => 89.2, 'map_y' => 3.0, 'map_width' => 9.8, 'map_height' => 31.0,
                'facilities' => [
                    ['name' => 'Lapangan Futsal & Voli', 'quantity' => 1],
                    ['name' => 'Ring Basket Interlock', 'quantity' => 2],
                    ['name' => 'Tiang Bendera Upacara', 'quantity' => 1],
                ],
            ],
        ];

        foreach ($rooms as $roomData) {
            $facilities = $roomData['facilities'] ?? [];
            unset($roomData['facilities']);

            $slug = $roomData['slug'];
            $roomData = array_merge($roomData, self::HOTSPOT_FIXES[$slug] ?? []);
            $roomData['image'] = self::ROOM_IMAGES[$slug] ?? null;
            $door = CampusWalkwaySeeder::DOORS[$slug] ?? null;
            $roomData['map_node_id'] = $door ? $walkway->nodeIds[$door] : null;

            $room = Room::create($roomData);

            foreach ($facilities as $facility) {
                Facility::create([
                    'room_id' => $room->id,
                    'name' => $facility['name'],
                    'icon' => $facility['icon'] ?? 'check',
                    'quantity' => $facility['quantity'] ?? 1,
                    'description' => $facility['description'] ?? null,
                ]);
            }
        }
    }
}
