import {
  Aperture,
  BriefcaseBusiness,
  Brush,
  CakeSlice,
  Calculator,
  Camera,
  ChefHat,
  Clapperboard,
  Code,
  Coffee,
  CookingPot,
  Cpu,
  CreditCard,
  Croissant,
  Database,
  Factory,
  FileText,
  Film,
  FlaskConical,
  GitBranch,
  GraduationCap,
  Handshake,
  Landmark,
  Laptop,
  Leaf,
  Microscope,
  Package,
  Palette,
  PenTool,
  Printer,
  ScrollText,
  ShieldCheck,
  Smartphone,
  Sparkles,
  SprayCan,
  Store,
  Target,
  TrendingUp,
} from "lucide-react";

const ICONS = {
  Aperture,
  BriefcaseBusiness,
  Brush,
  CakeSlice,
  Calculator,
  Camera,
  ChefHat,
  Clapperboard,
  Code,
  Coffee,
  CookingPot,
  Cpu,
  CreditCard,
  Croissant,
  Database,
  Factory,
  FileText,
  Film,
  FlaskConical,
  GitBranch,
  GraduationCap,
  Handshake,
  Landmark,
  Laptop,
  Leaf,
  Microscope,
  Package,
  Palette,
  PenTool,
  Printer,
  ScrollText,
  ShieldCheck,
  Smartphone,
  Sparkles,
  SprayCan,
  Store,
  Target,
  TrendingUp,
};

/** Ikon lucide berdasarkan nama yang disimpan di data jurusan. */
export default function JurusanIcon({ name, size = 18, className = "" }) {
  const Icon = ICONS[name] ?? Sparkles;
  return <Icon size={size} className={className} aria-hidden="true" />;
}
